### ISSUE TITLE
User systems in node

### ISSUE THREAD

**Issue by geek** [nodeconf/US-CFP#1]
[Reza Akhavan](https://github.com/jedireza) has built a couple of repos around user systems in node using express and hapi.  This is one of those problems that we all have likely had to deal with at one time or another, and so it seems fitting for a talk.

Here are the repos: https://github.com/jedireza/frame and https://github.com/jedireza/drywall

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
