### ISSUE TITLE
Working with (different) Full-Stack frameworks in Node

### ISSUE THREAD

**Issue by schisma** [nodeconf/US-CFP#10]
This is something that I've been asking myself for a rather long time: There's no framework quite like Rails in Node, yet they all seem to embrace different features. I've tried some of them (MEAN, Compound, Geddy, Meteor...) but somehow couldn't decide on one because they all seemed incomplete in comparison to Rails.

I'd love to see what other Node developers think about this issue.

**Comment by jfhbrook** [comment]
Along the same vein, I'd love to see something about the challenges behind building full stack frameworks in node. A lot of the pieces are there, and people have tried to do this (or close to it) before with limited success (flatiron, big, MEAN, jugglingdb + ???, bookshelf + ???, sails, some internal work at Conde), From my own experiences I know that there are a number of node-specific challenges, such as trying to decide which database or databases to support in your O[R|D]M, dealing with nested dependencies vs peerDependencies vs trying to implement DI, choosing a validation strategy, choosing how to leverage existing tools, implementing relationships if using brongodb, and more. It's a whole thing. Seeing someone actually get into what's required for building a full-stack framework in node as compared to the state of the art, and acknowledging the hypermodular "node way" without being a framework hater, would be fantastic.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
