### ISSUE TITLE
Progressive enhancement in MVC

### ISSUE THREAD

**Issue by bevacqua** [nodeconf/US-CFP#11]
I'm increasingly interested in progressively enhanced human experiences on the web, something that I think we started losing somewhere along the line. Frameworks like Angular promote dedicated client-side rendering which offers productivity at the cost of performance, accessibility and usability.

Taunus is a framework that puts progressive enhancement first, I think it'd be interesting to have a presentation about it.

[Stop Breaking the Web](http://ponyfoo.com/articles/stop-breaking-the-web)

[Taunus](http://taunus.bevacqua.io/)

[Taunus Source](https://github.com/taunus/taunus)

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
