### ISSUE TITLE
File Watching in Node

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodeconf/US-CFP#13]
the current approach to file watching is a bit janky.  Cross platform file watching is a difficult beast, especially considering the number of things that are inconsistent across platforms (symlinks, TEMPDIR)

I had a great chat with @othiym23 about why things are designed the way they are in libuv, and I think a talk discussing this topic would be very interesting.

**Comment by domenic** [comment]
+1, any talk that has a chance to delve into the platform-specific intricacies of libuv in order to explain higher-order wonkiness in node would be very interesting.

**Comment by othiym23** [comment]
I agree this is a good talk. I'd like to see discussion of:

* how and why this is a multiplatform issue
* how to practically deal with it an application level (chokidar? fsevents?)
* why libuv handles it the way it does

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
