### ISSUE TITLE
NodeUp Live

### ISSUE THREAD

**Issue by rvagg** [nodeconf/US-CFP#14]
Can we please plan to do this properly this year!

/ @floating @dshaw @timoxley

**Comment by mikeal** [comment]
We can do this as an evening event.

**Comment by rvagg** [comment]
I'd love to get some critique (from anyone!) of the 2 CampJS Live NodeUp shows to see if we can improve on that format

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
