### ISSUE TITLE
Create and Hack your own Musical Instruments with NodeBots

### ISSUE THREAD

**Issue by julianduque** [nodeconf/US-CFP#15]
I love music but I'm not a musician, I've seen some interesting musical projects (for example https://github.com/substack/baudio and https://github.com/substack/code-music-studio by @substack)

It would be interesting to build and hack your own musical instruments.

In the past [JSConf Argentina](http://jsconfar.com) I gave a talk about NodeBots and the NodeBots Community, I showed some music projects built using Node.js and Hardware (preview https://www.youtube.com/watch?v=I4VkZ5H9PE8), this can involve from simple push buttons to create a drum kit to nice rgb led strips as the ones used by @nodebotanist in her awesome nodebots projects.

A preview of some prototypes I've been working on:

[Theremin](https://vine.co/v/O1zKUlTjrzA)
[Gaita with RGB Leds](https://vine.co/v/O5YuU215w65)

**Comment by julianduque** [comment]
[Theremin](https://vine.co/v/O1zKUlTjrzA)
[Gaita with RGB Leds](https://vine.co/v/O5YuU215w65)

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
