### ISSUE TITLE
Isomorphic Javascript

### ISSUE THREAD

**Issue by Marlena** [nodeconf/US-CFP#16]
There could be a few different approaches to talks on this subject.  

[This article] (http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/) on isomorphic javascript is an interesting read and would make for an interesting talk.

The article mentions that Meteor.js is one of the largest isomorphic projects.  It would be interesting to hear someone from the project speak to that.

Isomorphic javascript and React.js -- Has anyone written something that goes further than the tutorial?  That would be fun to see.

**Comment by jedireza** [comment]
I'd like to see more talks on this also. At Yahoo we've been working on isomorphic [Flux applications](https://github.com/yahoo/fluxible-app).

Isomorphic applications have special audiences. Developers probably won't need to be in that head space until SEO needs consideration while also being a web app. Airbnb being a great example. A blog probably wouldn't need to be isomorphic. I forget who, but I remember someone saying that making your app isomorphic is an _optimization_.

Good idea for a talk :+1:

**Comment by binarymist** [comment]
Yip. Plus 1. Would be good to see and hear.

**Comment by Qard** [comment]
:+1: I'm working on an isomorphic koa/react/socket.io stack at the moment. Lots of fun. :)

**Comment by gunnik** [comment]
:+1:

**Comment by mavin** [comment]
:+1:

**Comment by mdp** [comment]
We just had @jedireza give a talk on Isomorphic Fluxible apps (fluxible.io) at our SF JS Breakfast meetup, would be a good talk for NodeConf.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
