### ISSUE TITLE
Develop Desktop Applications with Node.js

### ISSUE THREAD

**Issue by julianduque** [nodeconf/US-CFP#17]
I think this is also an interesting topic to heard about it, I have seem some cool desktop applications made using Node.js and node-webkit

[https://nodesource.com/blog/node-desktop-applications](https://nodesource.com/blog/node-desktop-applications)

**Comment by ix** [comment]
:+1:

**Comment by beaugunderson** [comment]
:+1:, particularly interested in techniques to integrate with OS-specific features (full screen, global hotkeys, etc.)

**Comment by roczinskisquared** [comment]
yes please.

**Comment by gunnik** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
