### ISSUE TITLE
The human debugger - debugging node without tooling

### ISSUE THREAD

**Issue by geek** [nodeconf/US-CFP#18]
I'd like to see @hueniverse talk about debugging node issues.

**Comment by dlai0001** [comment]
:+1:

**Comment by pvenkatakrishnan** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
