### ISSUE TITLE
State of IO

### ISSUE THREAD

**Issue by arb** [nodeconf/US-CFP#19]
An honest and open discussion of the current status of Joyent/Node and IO.js. Where they are in relation to each other, what the future looks like, and how it impacts the community. Even a Q&A format would be good provided the person presenting was in a position to give the best answers.

**Comment by amark** [comment]
Yes please. I'm super confused about this since I don't follow much stuff. Would love to get an honest break down of what is going on.

**Comment by wpears** [comment]
+1

**Comment by mavin** [comment]
:+1:

**Comment by gchaturvedi** [comment]
:+1:

**Comment by mikeal** [comment]
While I like the sentiment I don't think we're have a *single* talk about this. The reality is that IO sort of owns the future of "Node" and there are several talks about the future of Node which are, of course, about io.js. Something like a "state of the union" for IO would be talks about the roadmap which dozens of people will be giving all over the world using the open source slide deck we've put out :) http://roadmap.iojs.org

**Comment by ismyrnow** [comment]
The JavaScript Jabber podcast hosted @isaacs and @mikeal a few weeks ago ([link](http://devchat.tv/js-jabber/147-jsj-io-js-with-isaac-schleuter-and-mikeal-rogers)) to talk about io.js, and I think they did a great job representing the "state of the union", at least at the time.

The thing that is most likely to change in the near future is progress on reconciling node.js and io.js, which seems to be desired, but can't be predicted.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
