### ISSUE TITLE
live battle between backend frameworks

### ISSUE THREAD

**Issue by fibric** [nodeconf/US-CFP#2]
hi,

i think nodeconf is different than any other conf (except taco conf ^-^) lets show it.
so why not just let representatives of each node backend framework do a live code session - against each other.

each framework guy has to solve the same problem in same time.

my backend proposals are:
[sailsjs](http://sailsjs.org/)
[vaticanjs](http://www.vaticanjs.info/)
[feathersjs](http://feathersjs.com/)

problem background:
star wars 7 is close (12 month still)
problem environment:
here is a nice data centric api: [http://swapi.co/](swapi.co)
problem to solve:
use picture service like flickr, instagram, etc to enrich star wars api with pictures.

when users query for x-wing then a collection of pictures maybe shown nearby available data from swapi.

does it make any sense?

**Comment by mikermcneil** [comment]
+1000

**Comment by roczinskisquared** [comment]
yes, yes and yes. I'd like a set of tasks which exposes the benefits of using one of the other. And would like to see Hapi in the m8x.

**Comment by tjwebb** [comment]
heh, this is an awesome idea. @mikermcneil you should show up and beat everyone using treeline from your iPhone :)

**Comment by fibric** [comment]
looks like it's not seen by @mikeal because its not listed here http://nodeconf.github.io/website/

**Comment by mikeal** [comment]
I've seen it :)

This isn't a good fit for the formal content because of the format constraints but I'm considering it for an evening event.

**Comment by fibric** [comment]
a streamed event? ;-)
still 7 time zones ahead of you aka utc+1 aka germany :D

**Comment by mikeal** [comment]
> a streamed event?

nope.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
