### ISSUE TITLE
Node community in China 

### ISSUE THREAD

**Issue by groundwater** [nodeconf/US-CFP#20]
I would like to recommend we invite @dead-horse to speak from Alibaba in Hangzhou China.

I recently spoke at JSConfa China as a last-minute add-on, and @dead-horse was a tremendous support. He helped me adapt my presentation in both language, content, and style to better fit the audience, and he co-presented the difficult parts during my talk.

The node community in China is large and growing. @dead-horse along with other awesome people help run the China mirror of npm, which faces all sorts of interesting challenges related to the firewall.

If anyone has other active node community members from China they would recommend please do so.

Please also be aware that anyone speaking from China will need ~2mo leeway for travel and Visa arrangements.

**Comment by domenic** [comment]
+1 to this topic, I really enjoyed HuJS in Shanghai a few years ago where it became apparent there's this whole other world that we normally don't get to see into because of the language barriers. I'd love to learn e.g. what's popular in China, what's different in coding styles or practices or adoption rates or... So much interesting stuff there.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
