### ISSUE TITLE
Native to JS Best Practices

### ISSUE THREAD

**Issue by trevnorris** [nodeconf/US-CFP#21]
Recently it's become very cheap to call into C++ from JS. Though pending that the API is done correctly. I would like to see a talk that covers this stuff. e.g. The fact that every C++ from JS call is implicitly wrapped in a `HandleScope`, so they're almost never necessary. Or get into the performance cheats between storing flags in external memory that are easily shared between JS and C++. Also how working with object properties in C++ should be pushed back to JS land.

There will probably be a section on https://github.com/rvagg/nan, but I'd like the emphasis to be on how users should feel more confident to get the performance results they're looking for, and not be afraid of writing native modules.

Possibly add a brief primer on how to write applications from scratch that easily allow these types of improvements in the future. W/o needing to work around past cruft.

**Comment by springmeyer** [comment]
Fantastic proposal @trevnorris.

**Comment by helvitismaddi** [comment]
+1

**Comment by gunnik** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
