### ISSUE TITLE
Application profiling and advanced optimization techniques

### ISSUE THREAD

**Issue by TheEwok** [nodeconf/US-CFP#22]
Specifically profiling in operating systems that do not support DTrace.

**Comment by jedireza** [comment]
:+1:

**Comment by Qard** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
