### ISSUE TITLE
Reactive Programming in JavaScript

### ISSUE THREAD

**Issue by mattpodwysocki** [nodeconf/US-CFP#23]
Reactive Programming has been a hot topic as of late, with Facebook's React, Angular, and Ember on the front end, and libraries such as RxJS, Bacon.js, and Highland.  But can we separate the hype from the reality?  What exactly is reactive programming?  Is it just responding to events in a scalable manner or is there more to it than that?  Are there patterns we can learn that help us build responsive applications to load, and ultimately responsive to the user?

**Comment by selfcontained** [comment]
:+1: Talking about architectures/patterns that support this, without framework hype, would be awesome.  The concept of one-way data flow could be a great talk in it's own imo, the benefits, principles etc.

**Comment by gunnik** [comment]
:+1:

**Comment by mavin** [comment]
:+1:

**Comment by dibyom** [comment]
:+1:

**Comment by wonderdogone** [comment]
+1

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
