### ISSUE TITLE
Level Up in Node: Beginner to Advanced, Browser to Server

### ISSUE THREAD

**Issue by llkats** [nodeconf/US-CFP#24]
You've been developing in the browser for years (or months. Or weeks!) You know JavaScript. You're excited to jump in writing JavaScript on the server with Node! You do the Nodeschool workshoppers. You read all the blogs. You make a few little web apps with Express or Hapi. So why do you still feel lost when you sit down to work with Node?

What does a developer who knows very little about back-end or systems programming need to know in order to create amazing things with Node? What concepts, responsibilities, and tasks do systems deal with, and how do people use Node to solve back-end problems?

Submitted with encouragement and help from @groundwater. Would love to expand on concrete subjects that would be useful for front-end developers to know.

**Comment by jedireza** [comment]
:+1:

**Comment by RuthieB** [comment]
A+! I hope I get to see this in person!

**Comment by groundwater** [comment]
:heart:

**Comment by amark** [comment]
Yes! I started with HTML/CSS and frontend JS - and that UX side of things is still where my passion is. But a good UX requires connecting to other things and not losing stuff on refresh, thus I had to learn backend. I still struggle with it to this day still, and will probably submit a similar issue.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
