### ISSUE TITLE
Intro to native modules

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodeconf/US-CFP#25]
I would love to see an introductory talk about writing a native module. This talk would be a corollary to #21 (perhaps even back-to-back or dual speaker talk).

When I wrote my first native module, I was kinda lost at first, despite the fact that I know Node.js and C++ well due to all of the JavaSscript/V8 specifics and relative lack of documentation at the conceptual level. Topics I would like to see covered: V8 API concepts (this is how an object is represented in C++, this is how you call a function in JS, etc), using https://github.com/rvagg/nan to write synchronous and asynchronous functions, argument validation, etc.

**Comment by Qard** [comment]
:+1:

**Comment by julianduque** [comment]
+1000

**Comment by helvitismaddi** [comment]
+1 for sure!

**Comment by gunnik** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
