### ISSUE TITLE
NodeBots

### ISSUE THREAD

**Issue by bryan-m-hughes** [nodeconf/US-CFP#26]
We gotta have some NodeBots at NodeConf of course! A couple of possible topics off the top of my head:

- Johnny-Five in the browser via Node-Webkit
- Wearables
- State of NodeBots. There are several startups in the bay area and elsewhere doing some exciting NodeBots work. Lots of new hardware and platforms coming out, and J5 support is growing fast.
- Adding support for new platforms to Johnny-Five using [board-io](https://github.com/achingbrain/board-io)

**Comment by julianduque** [comment]
+1

**Comment by nodebotanist** [comment]
I could do something with state of nodebots. Or we could do nodebots live! Episode 3. Thoughts

**Comment by bryan-m-hughes** [comment]
+1 @nodebotanist. Love the idea of another NodeBots live!

**Comment by nvcexploder** [comment]
+1 for NodeBots live!

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
