### ISSUE TITLE
Measuring modules

### ISSUE THREAD

**Issue by mikolalysenko** [nodeconf/US-CFP#27]
It would be nice to see some statistics/discussion of what makes a good module.

Now that npm has so many packages sitting around, it would be neat to take a step back and look for patterns in all the data.  What features consistently make for good modules (as in fast, and with few errors)?  And what makes a module popular?

Are there things we can do better here or patterns that we should be promoting/discouraging?

**Comment by binarymist** [comment]
This would be great. Especially in terms of security. Our developers are pulling so much untrusted code into their projects and well, just trusting it. There's a new specification that addresses just that: http://www.w3.org/TR/SRI/ Firefox and Chrome have initial implementations of this new specification.

I'm also working on a dynamic analysis tool for JavaScript to raise red flags when you're trusting code with vulnerabilities in it.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
