### ISSUE TITLE
No Back End

### ISSUE THREAD

**Issue by amark** [nodeconf/US-CFP#29]
Piggy backing off #24 , I'd like to see more talks around how new/early/non-developers can learn to easily make websites and apps without having to learn the complexities of building a backend. Thus noBackend.

Things like Firebase, Hood.ie, Parse, Deployd, etc. - and my [open source project](http://github.com/amark/gun). At JSFest I [talked](https://github.com/jsfest/oakland-cfp/issues/55) about my crazy metaphysical journey of learning to become a developer, questioning all assumptions. Now, it might be nice to talk about the tools (and their assumptions) that make things easier for newbies.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
