### ISSUE TITLE
Best Practices and Architecture for node systems

### ISSUE THREAD

**Issue by dlai0001** [nodeconf/US-CFP#3]
What are the best practices when dealing with a distributed system?

How do you set it up for dev, testing, staging, and production?

How do you ensure redundancy, speed, and availability?

**Comment by lazychino** [comment]
:+1:

**Comment by gunnik** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
