### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by ranman** [nodeconf/US-CFP#30]
I'd love to see a presentation about AWS's new Lambda service:http://aws.amazon.com/lambda/

**Comment by Qard** [comment]
:+1:  I'm curious to see how people use it or think it could be used.

**Comment by dlai0001** [comment]
:+1:

**Comment by gunnik** [comment]
:+1:

**Comment by ranman** [comment]
I've built a few websites with it now including http://apodtwitter.com
I made a quick crashcourse here: https://speakerdeck.com/ranman/aws-lambda-crash-course

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
