### ISSUE TITLE
Working with Binary Data + Bit Operations using ArrayBuffers, Fringe Projects

### ISSUE THREAD

**Issue by keithwhor** [nodeconf/US-CFP#32]
I find there's not a lot of widespread information on the usefulness of ArrayBuffers and how quickly they perform in V8 + neat uses of them (especially when used with bit operations). I'd love to see some talks about more esoteric uses of JS / node.

I first fell in love with ArrayBuffers when they became a necessity for browser-based work (using webworkers + transferable objects) but since have found myself [translating genetic sequences into binary in node for ultra-fast sequence alignment](https://github.com/keithwhor/NtSeq) as well as things like storing Brainfuck instructions (translating the instruction set into binary) for playing with genetic algorithms without having to do string manipulation (array accession + bit shifts to read commands, mutating instructions by randomly flipping bits).

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
