### ISSUE TITLE
Benchmarks and performance analysis

### ISSUE THREAD

**Issue by ryanseys** [nodeconf/US-CFP#33]
I'd love to see a talk on what different tools are available for benchmarking and performance analysis of node applications or modules. Perhaps something where DevTools / node inspector / flamecharts / dtrace / memdumps are used to find highly-accessed or slow parts of the application, or parts that eat up lots of memory or create unnecessarily large stacks. For example, this can be used in comparing the overall performance of two different modules accomplishing the same task such as making an API call or processing a high-volume of data.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
