### ISSUE TITLE
Using ES6 With NodeJS

### ISSUE THREAD

**Issue by jkresner** [nodeconf/US-CFP#34]
This is an old post (about 5 months ago) and I have loads more knowledge now and do things a bit differently including how we bootstrap ES6. Will write a new post in the next few weeks and share it then:

https://www.airpair.com/javascript/posts/using-es6-harmony-with-nodejs

**Comment by dmh2000** [comment]
+1

**Comment by randallmeeker** [comment]
:+1:

**Comment by jkresner** [comment]
@mikeal are the speakers finalized? I was thinking of doing a blog series "Advanced MEAN-Stack"

- p1: Tips & Techniques for Testing BIG Apps
- p2: BIG Schema, SMALL Payloads: MongoDB & Express Data Patterns
- p3: ES6 on NodeJS
- p4: Semantic Middleware
- p5: Lazy Loading Requires for SPPPEEED
- p6: Browserify & Packaging For Distribution
- p7: Hyrid Client-Server Template Techniques
- p8: Analytics & (airpair.com's) Real-Time "God View"

I think I could package it into a killer talk.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
