### ISSUE TITLE
Building APIs using Swagger and Node.Js

### ISSUE THREAD

**Issue by prabhatjha** [nodeconf/US-CFP#35]
Set of OSS tools that you need to design and build Enterprise-class APIs entirely in Node.js using Swagger specification and deploy them on any Node.js runtime system. 

Relevant projects:

Swagger 2.0 Spec: https://github.com/swagger-api/swagger-spec
Online Editor: https://github.com/swagger-api/swagger-editor
Routing and Validation: https://github.com/apigee-127/swagger-tools
CLI, Project scaffolding, OAuth etc: https://github.com/apigee-127/a127

**Comment by gunnik** [comment]
:+1:

**Comment by DJCordhose** [comment]
+1

**Comment by helvitismaddi** [comment]
+1 for sure!

**Comment by schebrolu** [comment]
:+1:

**Comment by btallman** [comment]
+1

**Comment by illicium** [comment]
:shipit:

**Comment by dibyom** [comment]
:+1:

**Comment by anubis05** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by anil614sagar** [comment]
+1

**Comment by harishdeshmukh** [comment]
https://camo.githubusercontent.com/a2840914d539225aaf8d395397d8dbc488a0740d/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67

**Comment by jwest-apigee** [comment]
+1

**Comment by sananthula** [comment]
+1

**Comment by mikedunker-apigee** [comment]
:+1:

**Comment by pvenkatakrishnan** [comment]
also @tlivings has been doing similar work here https://github.com/krakenjs?query=swaggerize

**Comment by tlivings** [comment]
Have a presentation along these lines of "scaling enterprise API development with swagger and node.js" but haven't committed to the conference so likely not in time.

Great topic though, and a lot to discuss - including other specifications like raml.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
