### ISSUE TITLE
Node conspiracy theories

### ISSUE THREAD

**Issue by geek** [nodeconf/US-CFP#36]
Speaker: @arb

Adam has more than a few theories about node/io conspiracies.  I would expect this to be a short talk that provides a lot of entertainment value.

**Comment by jaw187** [comment]
![](http://s3-ec.buzzfed.com/static/enhanced/webdr01/2013/3/3/13/enhanced-buzz-8047-1362334165-4.jpg)

**Comment by Qard** [comment]
I look forward to all the conspiracy theories about what Ryan Dahl is up to now. :P

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
