### ISSUE TITLE
Sail.js in action 

### ISSUE THREAD

**Issue by mrlami** [nodeconf/US-CFP#4]

**Comment by scriptnull** [comment]
+1 for sails .

**Comment by gunnik** [comment]
:+1:

**Comment by randallmeeker** [comment]
:+1:

**Comment by tjwebb** [comment]
We love this idea! Let us know if we can help.

-- the sails.js team

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).

**Comment by tjwebb** [comment]
Sorry to hear that @mikeal. Thanks for the update
