### ISSUE TITLE
Creating REST APIs with node

### ISSUE THREAD

**Issue by gunnik** [nodeconf/US-CFP#42]
I'd love to see a talk covering creating REST APIs with node.js/io.js. Not really talking about any one module or toolset but more a coverage of best practices, common pitfalls and hopefully some production experiences and insight.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
