### ISSUE TITLE
What is it like to test every npm module?

### ISSUE THREAD

**Issue by diasdavid** [nodeconf/US-CFP#43]
@apocas has been doing some solid work on nodechecker for a while now and he does have some funny and interesting battle stories of what is to continuously test every single module in npm, which I believe were only shared in our local meetup. Ah, he also created [dockerode](https://www.npmjs.com/package/dockerode)

Check the project here: http://nodechecker.com/
Github here: https://github.com/apocas

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
