### ISSUE TITLE
hystrix with node.js apps.

### ISSUE THREAD

**Issue by pvenkatakrishnan** [nodeconf/US-CFP#44]
I am currently working on this for Paypal and is not a completely open source project but would be able to create a demo that can be a more generic one that will be of use to the community as a whole.
Would really love to hear from what other people have done along the lines   of monitoring and resilience with node.js apps.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
