### ISSUE TITLE
RealTime Pub/Sub with DDS inside node

### ISSUE THREAD

**Issue by gianpiero** [nodeconf/US-CFP#45]
I am interested on how RealTime Pub/Sub (in particular OMG DDS) can be easily integrated with nodejs. I am working on something similar and I am not a node or javascript expert so I would love to know what the community thinks.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
