### ISSUE TITLE
Node powering desktop apps via projects like Atom Shell

### ISSUE THREAD

**Issue by emorikawa** [nodeconf/US-CFP#47]
It seems that an increasingly large number of desktop apps I use every day (like Slack, [Atom](https://github.com/atom/atom), and others) are backed by Node as bundled up in projects like [Atom Shell](https://github.com/atom/atom-shell).

I'm personally working on a hyper-extensible [desktop email client](https://www.nilas.com/blog/splitting-the-atom) that's all React with a Node backend on Atom Shell in Coffeescript. I'd love to see this hybrid world take off more and learn about how people are using this medium.

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
