### ISSUE TITLE
JS == art

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [nodeconf/US-CFP#5]
I love code art, creative coding, generative art, whatever the name you apply to it. We have all these tools and all this knowledge as developers, and I love when people use them in unexpected ways or bend them to make something amazing.

Using D3, a data visualization tool, to make generative art. Glitching out images to make something crazy. L-systems to create motion or color patterns.

We all love coding, and many people don't think about creating something expressive rather than functional. We can all be artists if we want to be.

I talk about this stuff a lot (most recently at [Nodevember](https://www.youtube.com/watch?v=kovJHzQNsg0)), and would love to do so again. But if not me, someone on this topic would be great, because we could be using the right side of our brain in better conjunction with our left if we try.

Let's make art!

**Comment by shama** [comment]
+1

**Comment by hughsk** [comment]
+1

**Comment by julianduque** [comment]
+1

**Comment by beaugunderson** [comment]
+1, would be awesome to see one or more of:

- [@katierosepipkin](https://twitter.com/katierosepipkin)
  - twitter bots like [@tiny_star_field](https://twitter.com/tiny_star_field) in node.js
  - websites like [inflorescence.city](http://inflorescence.city/) & [train.neocities.org](http://train.neocities.org/)
- @jennschiffer 
  - [vart.institute](http://vart.institute/)
  - [make8bitart.com](http://make8bitart.com/)
  - (many other things in JS)
- @ednapiranha
  - [revisit.link](http://revisit.link/)
  - [meatspac.es](https://chat.meatspac.es/)

talk about this if they're interested in speaking!

**Comment by nvcexploder** [comment]
+1

In addition to those listed above, @rachelnabors would be an excellent consideration.

**Comment by rachelnabors** [comment]
Thanks, Ben :) I also might have some suggestions. But I think they're more "code as a means to art" than "code as art."

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
