### ISSUE TITLE
Giving Back and Pushing Forward in the Node Community

### ISSUE THREAD

**Issue by phildini** [nodeconf/US-CFP#6]
Things that matter to me:

- How the node community is onboarding new members, especially those underrepresented in tech
- How the node community is supporting new members past the onboarding/pipeline phase
- Where and how the node community gives back to other communities, either in time or resources to charities and nonprofits

**Comment by jasonrhodes** [comment]
+1

**Comment by julianduque** [comment]
+1

**Comment by a0viedo** [comment]
+1

**Comment by pvenkatakrishnan** [comment]
:+1:

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
