### ISSUE TITLE
Mastering front-end codebases using static analysis

### ISSUE THREAD

**Issue by mrjoelkemp** [nodeconf/US-CFP#7]
Relevant projects and modules:
- https://github.com/mrjoelkemp/sublime-dependents
- https://github.com/mrjoelkemp/node-dependents
- https://github.com/mrjoelkemp/node-app-root
- https://github.com/mrjoelkemp/node-dependency-tree
- https://github.com/mrjoelkemp/node-precinct

Some talks that I've given on static analysis applications:
- https://skillsmatter.com/skillscasts/5776-using-static-analysis-to-give-build-tools-a-brain
- https://www.youtube.com/watch?v=X7qXPsfJv90

**Comment by jarofghosts** [comment]
:+1: , really anything about using node tools and concepts on/for the frontend

**Comment by Munter** [comment]
I should throw https://github.com/assetgraph/assetgraph and https://github.com/assetgraph/assetgraph-builder into the mix here. Quite relevant for this topic
