### ISSUE TITLE
hacking on node itself

### ISSUE THREAD

**Issue by xjamundx** [nodeconf/US-CFP#8]
I'd love to learn more about hacking on node itself. How does it work.

**Comment by timoxley** [comment]
+1 would love to see a "Guided Tour of the Node Codebase". 

e.g. what does node do on startup, how do native module works, what steps happen during compilation, gyp vs ninja vs ???, how the tests/benchmarks work, how data flows through a tcp/http server, how data flows through an fs.readFile, what are birds, etc.

**Comment by a0viedo** [comment]
+1

**Comment by raptastics** [comment]
@timoxley What do you mean by birds? I tried to search but am turning nothing up.

**Comment by timoxley** [comment]
@raptastics entirely [off topic](https://www.youtube.com/watch?v=Kh0Y2hVe_bw).

**Comment by dibyom** [comment]
+1

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
